// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/api.proto

package api // import "github.com/nada-wagahai/kifulog/go/proto/api"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import kifu "github.com/nada-wagahai/kifulog/go/proto/kifu"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Step struct {
	KifuId               string         `protobuf:"bytes,1,opt,name=kifu_id,json=kifuId,proto3" json:"kifu_id,omitempty"`
	Seq                  int32          `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	Finished             bool           `protobuf:"varint,3,opt,name=finished,proto3" json:"finished,omitempty"`
	StartTs              int64          `protobuf:"varint,4,opt,name=start_ts,json=startTs,proto3" json:"start_ts,omitempty"`
	Players              []*kifu.Player `protobuf:"bytes,5,rep,name=players,proto3" json:"players,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Step) Reset()         { *m = Step{} }
func (m *Step) String() string { return proto.CompactTextString(m) }
func (*Step) ProtoMessage()    {}
func (*Step) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_d3b4c88d4e011d4b, []int{0}
}
func (m *Step) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Step.Unmarshal(m, b)
}
func (m *Step) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Step.Marshal(b, m, deterministic)
}
func (dst *Step) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Step.Merge(dst, src)
}
func (m *Step) XXX_Size() int {
	return xxx_messageInfo_Step.Size(m)
}
func (m *Step) XXX_DiscardUnknown() {
	xxx_messageInfo_Step.DiscardUnknown(m)
}

var xxx_messageInfo_Step proto.InternalMessageInfo

func (m *Step) GetKifuId() string {
	if m != nil {
		return m.KifuId
	}
	return ""
}

func (m *Step) GetSeq() int32 {
	if m != nil {
		return m.Seq
	}
	return 0
}

func (m *Step) GetFinished() bool {
	if m != nil {
		return m.Finished
	}
	return false
}

func (m *Step) GetStartTs() int64 {
	if m != nil {
		return m.StartTs
	}
	return 0
}

func (m *Step) GetPlayers() []*kifu.Player {
	if m != nil {
		return m.Players
	}
	return nil
}

type Comment struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Text                 string   `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	Owned                bool     `protobuf:"varint,4,opt,name=owned,proto3" json:"owned,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Comment) Reset()         { *m = Comment{} }
func (m *Comment) String() string { return proto.CompactTextString(m) }
func (*Comment) ProtoMessage()    {}
func (*Comment) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_d3b4c88d4e011d4b, []int{1}
}
func (m *Comment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Comment.Unmarshal(m, b)
}
func (m *Comment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Comment.Marshal(b, m, deterministic)
}
func (dst *Comment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Comment.Merge(dst, src)
}
func (m *Comment) XXX_Size() int {
	return xxx_messageInfo_Comment.Size(m)
}
func (m *Comment) XXX_DiscardUnknown() {
	xxx_messageInfo_Comment.DiscardUnknown(m)
}

var xxx_messageInfo_Comment proto.InternalMessageInfo

func (m *Comment) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Comment) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Comment) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *Comment) GetOwned() bool {
	if m != nil {
		return m.Owned
	}
	return false
}

type KifuRequest struct {
	KifuId               string   `protobuf:"bytes,1,opt,name=kifu_id,json=kifuId,proto3" json:"kifu_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KifuRequest) Reset()         { *m = KifuRequest{} }
func (m *KifuRequest) String() string { return proto.CompactTextString(m) }
func (*KifuRequest) ProtoMessage()    {}
func (*KifuRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_d3b4c88d4e011d4b, []int{2}
}
func (m *KifuRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KifuRequest.Unmarshal(m, b)
}
func (m *KifuRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KifuRequest.Marshal(b, m, deterministic)
}
func (dst *KifuRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KifuRequest.Merge(dst, src)
}
func (m *KifuRequest) XXX_Size() int {
	return xxx_messageInfo_KifuRequest.Size(m)
}
func (m *KifuRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_KifuRequest.DiscardUnknown(m)
}

var xxx_messageInfo_KifuRequest proto.InternalMessageInfo

func (m *KifuRequest) GetKifuId() string {
	if m != nil {
		return m.KifuId
	}
	return ""
}

type BoardRequest struct {
	BoardId              string   `protobuf:"bytes,1,opt,name=board_id,json=boardId,proto3" json:"board_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BoardRequest) Reset()         { *m = BoardRequest{} }
func (m *BoardRequest) String() string { return proto.CompactTextString(m) }
func (*BoardRequest) ProtoMessage()    {}
func (*BoardRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_d3b4c88d4e011d4b, []int{3}
}
func (m *BoardRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BoardRequest.Unmarshal(m, b)
}
func (m *BoardRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BoardRequest.Marshal(b, m, deterministic)
}
func (dst *BoardRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BoardRequest.Merge(dst, src)
}
func (m *BoardRequest) XXX_Size() int {
	return xxx_messageInfo_BoardRequest.Size(m)
}
func (m *BoardRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BoardRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BoardRequest proto.InternalMessageInfo

func (m *BoardRequest) GetBoardId() string {
	if m != nil {
		return m.BoardId
	}
	return ""
}

type BoardResponse struct {
	Board                *kifu.Board `protobuf:"bytes,1,opt,name=board,proto3" json:"board,omitempty"`
	Comments             []*Comment  `protobuf:"bytes,2,rep,name=comments,proto3" json:"comments,omitempty"`
	Steps                []*Step     `protobuf:"bytes,3,rep,name=steps,proto3" json:"steps,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *BoardResponse) Reset()         { *m = BoardResponse{} }
func (m *BoardResponse) String() string { return proto.CompactTextString(m) }
func (*BoardResponse) ProtoMessage()    {}
func (*BoardResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_d3b4c88d4e011d4b, []int{4}
}
func (m *BoardResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BoardResponse.Unmarshal(m, b)
}
func (m *BoardResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BoardResponse.Marshal(b, m, deterministic)
}
func (dst *BoardResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BoardResponse.Merge(dst, src)
}
func (m *BoardResponse) XXX_Size() int {
	return xxx_messageInfo_BoardResponse.Size(m)
}
func (m *BoardResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BoardResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BoardResponse proto.InternalMessageInfo

func (m *BoardResponse) GetBoard() *kifu.Board {
	if m != nil {
		return m.Board
	}
	return nil
}

func (m *BoardResponse) GetComments() []*Comment {
	if m != nil {
		return m.Comments
	}
	return nil
}

func (m *BoardResponse) GetSteps() []*Step {
	if m != nil {
		return m.Steps
	}
	return nil
}

type IndexRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IndexRequest) Reset()         { *m = IndexRequest{} }
func (m *IndexRequest) String() string { return proto.CompactTextString(m) }
func (*IndexRequest) ProtoMessage()    {}
func (*IndexRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_d3b4c88d4e011d4b, []int{5}
}
func (m *IndexRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IndexRequest.Unmarshal(m, b)
}
func (m *IndexRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IndexRequest.Marshal(b, m, deterministic)
}
func (dst *IndexRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IndexRequest.Merge(dst, src)
}
func (m *IndexRequest) XXX_Size() int {
	return xxx_messageInfo_IndexRequest.Size(m)
}
func (m *IndexRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IndexRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IndexRequest proto.InternalMessageInfo

type IndexResponse struct {
	Entries              []*IndexResponse_Entry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	RecentComments       []*Comment             `protobuf:"bytes,2,rep,name=recent_comments,json=recentComments,proto3" json:"recent_comments,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *IndexResponse) Reset()         { *m = IndexResponse{} }
func (m *IndexResponse) String() string { return proto.CompactTextString(m) }
func (*IndexResponse) ProtoMessage()    {}
func (*IndexResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_d3b4c88d4e011d4b, []int{6}
}
func (m *IndexResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IndexResponse.Unmarshal(m, b)
}
func (m *IndexResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IndexResponse.Marshal(b, m, deterministic)
}
func (dst *IndexResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IndexResponse.Merge(dst, src)
}
func (m *IndexResponse) XXX_Size() int {
	return xxx_messageInfo_IndexResponse.Size(m)
}
func (m *IndexResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_IndexResponse.DiscardUnknown(m)
}

var xxx_messageInfo_IndexResponse proto.InternalMessageInfo

func (m *IndexResponse) GetEntries() []*IndexResponse_Entry {
	if m != nil {
		return m.Entries
	}
	return nil
}

func (m *IndexResponse) GetRecentComments() []*Comment {
	if m != nil {
		return m.RecentComments
	}
	return nil
}

type IndexResponse_Entry struct {
	Id                   string     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Kifu                 *kifu.Kifu `protobuf:"bytes,2,opt,name=kifu,proto3" json:"kifu,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *IndexResponse_Entry) Reset()         { *m = IndexResponse_Entry{} }
func (m *IndexResponse_Entry) String() string { return proto.CompactTextString(m) }
func (*IndexResponse_Entry) ProtoMessage()    {}
func (*IndexResponse_Entry) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_d3b4c88d4e011d4b, []int{6, 0}
}
func (m *IndexResponse_Entry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IndexResponse_Entry.Unmarshal(m, b)
}
func (m *IndexResponse_Entry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IndexResponse_Entry.Marshal(b, m, deterministic)
}
func (dst *IndexResponse_Entry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IndexResponse_Entry.Merge(dst, src)
}
func (m *IndexResponse_Entry) XXX_Size() int {
	return xxx_messageInfo_IndexResponse_Entry.Size(m)
}
func (m *IndexResponse_Entry) XXX_DiscardUnknown() {
	xxx_messageInfo_IndexResponse_Entry.DiscardUnknown(m)
}

var xxx_messageInfo_IndexResponse_Entry proto.InternalMessageInfo

func (m *IndexResponse_Entry) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *IndexResponse_Entry) GetKifu() *kifu.Kifu {
	if m != nil {
		return m.Kifu
	}
	return nil
}

func init() {
	proto.RegisterType((*Step)(nil), "api.Step")
	proto.RegisterType((*Comment)(nil), "api.Comment")
	proto.RegisterType((*KifuRequest)(nil), "api.KifuRequest")
	proto.RegisterType((*BoardRequest)(nil), "api.BoardRequest")
	proto.RegisterType((*BoardResponse)(nil), "api.BoardResponse")
	proto.RegisterType((*IndexRequest)(nil), "api.IndexRequest")
	proto.RegisterType((*IndexResponse)(nil), "api.IndexResponse")
	proto.RegisterType((*IndexResponse_Entry)(nil), "api.IndexResponse.Entry")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// APIClient is the client API for API service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type APIClient interface {
	Index(ctx context.Context, in *IndexRequest, opts ...grpc.CallOption) (*IndexResponse, error)
	Kifu(ctx context.Context, in *KifuRequest, opts ...grpc.CallOption) (*kifu.Kifu, error)
	Board(ctx context.Context, in *BoardRequest, opts ...grpc.CallOption) (*BoardResponse, error)
}

type aPIClient struct {
	cc *grpc.ClientConn
}

func NewAPIClient(cc *grpc.ClientConn) APIClient {
	return &aPIClient{cc}
}

func (c *aPIClient) Index(ctx context.Context, in *IndexRequest, opts ...grpc.CallOption) (*IndexResponse, error) {
	out := new(IndexResponse)
	err := c.cc.Invoke(ctx, "/api.API/Index", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) Kifu(ctx context.Context, in *KifuRequest, opts ...grpc.CallOption) (*kifu.Kifu, error) {
	out := new(kifu.Kifu)
	err := c.cc.Invoke(ctx, "/api.API/Kifu", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) Board(ctx context.Context, in *BoardRequest, opts ...grpc.CallOption) (*BoardResponse, error) {
	out := new(BoardResponse)
	err := c.cc.Invoke(ctx, "/api.API/Board", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// APIServer is the server API for API service.
type APIServer interface {
	Index(context.Context, *IndexRequest) (*IndexResponse, error)
	Kifu(context.Context, *KifuRequest) (*kifu.Kifu, error)
	Board(context.Context, *BoardRequest) (*BoardResponse, error)
}

func RegisterAPIServer(s *grpc.Server, srv APIServer) {
	s.RegisterService(&_API_serviceDesc, srv)
}

func _API_Index_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IndexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).Index(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.API/Index",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).Index(ctx, req.(*IndexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_Kifu_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KifuRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).Kifu(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.API/Kifu",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).Kifu(ctx, req.(*KifuRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_Board_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BoardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).Board(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.API/Board",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).Board(ctx, req.(*BoardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _API_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.API",
	HandlerType: (*APIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Index",
			Handler:    _API_Index_Handler,
		},
		{
			MethodName: "Kifu",
			Handler:    _API_Kifu_Handler,
		},
		{
			MethodName: "Board",
			Handler:    _API_Board_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/api.proto",
}

func init() { proto.RegisterFile("proto/api.proto", fileDescriptor_api_d3b4c88d4e011d4b) }

var fileDescriptor_api_d3b4c88d4e011d4b = []byte{
	// 556 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x53, 0xcf, 0x6e, 0xd3, 0x4e,
	0x10, 0x96, 0xe3, 0xb8, 0x76, 0x26, 0x69, 0x9b, 0xdf, 0xfe, 0xa8, 0xea, 0x9a, 0x7f, 0xc1, 0x87,
	0xca, 0x48, 0x10, 0x4b, 0x41, 0x88, 0x73, 0x83, 0x38, 0x44, 0x08, 0xa9, 0x5a, 0x90, 0x90, 0xb8,
	0x44, 0x9b, 0x78, 0xe3, 0xac, 0x48, 0x76, 0x5d, 0xef, 0x46, 0x6d, 0x55, 0xe5, 0xc2, 0x13, 0x20,
	0xf1, 0x28, 0x3c, 0x0a, 0x47, 0xae, 0x3c, 0x08, 0xf2, 0xac, 0x13, 0x52, 0x55, 0x70, 0x9b, 0xf9,
	0xe6, 0x9b, 0xf1, 0x37, 0xfb, 0x8d, 0xe1, 0xb0, 0x28, 0x95, 0x51, 0x29, 0x2b, 0x44, 0x1f, 0x23,
	0xe2, 0xb2, 0x42, 0x44, 0x0f, 0x72, 0xa5, 0xf2, 0x05, 0xaf, 0xe0, 0x94, 0x49, 0xa9, 0x0c, 0x33,
	0x42, 0x49, 0x6d, 0x29, 0x51, 0xd7, 0xf6, 0x7c, 0x16, 0xb3, 0x95, 0x45, 0xe2, 0xaf, 0x0e, 0x34,
	0xdf, 0x1b, 0x5e, 0x90, 0x63, 0xf0, 0x2b, 0x78, 0x2c, 0xb2, 0xd0, 0xe9, 0x39, 0x49, 0x8b, 0xee,
	0x55, 0xe9, 0x28, 0x23, 0x5d, 0x70, 0x35, 0xbf, 0x08, 0x1b, 0x3d, 0x27, 0xf1, 0x68, 0x15, 0x92,
	0x08, 0x82, 0x99, 0x90, 0x42, 0xcf, 0x79, 0x16, 0xba, 0x3d, 0x27, 0x09, 0xe8, 0x36, 0x27, 0x27,
	0x10, 0x68, 0xc3, 0x4a, 0x33, 0x36, 0x3a, 0x6c, 0xf6, 0x9c, 0xc4, 0xa5, 0x3e, 0xe6, 0x1f, 0x34,
	0x39, 0x05, 0xbf, 0x58, 0xb0, 0x6b, 0x5e, 0xea, 0xd0, 0xeb, 0xb9, 0x49, 0x7b, 0xd0, 0xe9, 0xa3,
	0x90, 0x73, 0x04, 0xe9, 0xa6, 0x18, 0x7f, 0x04, 0xff, 0xb5, 0x5a, 0x2e, 0xb9, 0x34, 0xe4, 0x00,
	0x1a, 0x5b, 0x3d, 0x0d, 0x91, 0x11, 0x02, 0x4d, 0xc9, 0x96, 0x1c, 0xc5, 0xb4, 0x28, 0xc6, 0x15,
	0x66, 0xf8, 0x95, 0x41, 0x25, 0x2d, 0x8a, 0x31, 0xb9, 0x07, 0x9e, 0xba, 0x94, 0x3c, 0x43, 0x09,
	0x01, 0xb5, 0x49, 0x7c, 0x0a, 0xed, 0xb7, 0x62, 0xb6, 0xa2, 0xfc, 0x62, 0xc5, 0xb5, 0xf9, 0xeb,
	0xc6, 0xf1, 0x53, 0xe8, 0x0c, 0x15, 0x2b, 0xb3, 0x0d, 0xf1, 0x04, 0x82, 0x49, 0x95, 0xff, 0x61,
	0xfa, 0x98, 0x8f, 0xb2, 0x78, 0x0d, 0xfb, 0x35, 0x55, 0x17, 0x4a, 0x6a, 0x4e, 0x9e, 0x80, 0x87,
	0x35, 0x24, 0xb6, 0x07, 0x6d, 0xbb, 0xa2, 0xe5, 0xd8, 0x0a, 0x49, 0x20, 0x98, 0xda, 0xfd, 0x74,
	0xd8, 0xa8, 0x1f, 0xa2, 0x72, 0xb1, 0x5e, 0x9a, 0x6e, 0xab, 0xe4, 0x31, 0x78, 0xda, 0xf0, 0x42,
	0x87, 0x2e, 0xd2, 0x5a, 0x48, 0xab, 0xdc, 0xa2, 0x16, 0x8f, 0x0f, 0xa0, 0x33, 0x92, 0x19, 0xbf,
	0xaa, 0x95, 0xc6, 0xdf, 0x1d, 0xd8, 0xaf, 0x81, 0x5a, 0xcf, 0x00, 0x7c, 0x2e, 0x4d, 0x29, 0xb8,
	0x0e, 0x1d, 0x1c, 0x12, 0xe2, 0x90, 0x5b, 0xa4, 0xfe, 0x1b, 0x69, 0xca, 0x6b, 0xba, 0x21, 0x92,
	0x97, 0x70, 0x58, 0xf2, 0x29, 0x97, 0x66, 0xfc, 0x4f, 0x9d, 0x07, 0x96, 0x54, 0xa7, 0x3a, 0x7a,
	0x05, 0x1e, 0x0e, 0xba, 0xe3, 0xda, 0x23, 0x68, 0x56, 0xaf, 0x80, 0xae, 0xb5, 0x07, 0x60, 0x9f,
	0x04, 0x9d, 0x40, 0x7c, 0xf0, 0xd3, 0x01, 0xf7, 0xec, 0x7c, 0x44, 0x86, 0xe0, 0xa1, 0x2e, 0xf2,
	0xdf, 0xae, 0x46, 0xdc, 0x2c, 0x22, 0x77, 0x65, 0xc7, 0xe4, 0xcb, 0x8f, 0x5f, 0xdf, 0x1a, 0x1d,
	0x02, 0x78, 0xed, 0x02, 0x5b, 0xcf, 0xa0, 0x59, 0x4d, 0x26, 0x5d, 0xe4, 0xef, 0xd8, 0x1d, 0xed,
	0x7c, 0x37, 0xbe, 0x8f, 0x9d, 0x47, 0xe4, 0x7f, 0xec, 0xac, 0xf0, 0xf4, 0xa6, 0xbe, 0x85, 0x35,
	0x79, 0x07, 0x1e, 0xfa, 0x55, 0xcb, 0xd8, 0x3d, 0x85, 0x5a, 0xc6, 0x2d, 0xcb, 0xe3, 0x87, 0x38,
	0xec, 0x98, 0x1c, 0xe1, 0x30, 0xf4, 0x38, 0xbd, 0xd9, 0x1c, 0xcc, 0x7a, 0xd8, 0xff, 0xf4, 0x2c,
	0x17, 0x66, 0xbe, 0x9a, 0xf4, 0xa7, 0x6a, 0x99, 0x4a, 0x96, 0xb1, 0xe7, 0x97, 0x2c, 0x67, 0x73,
	0x66, 0x3f, 0xbc, 0x50, 0x79, 0x9a, 0xab, 0x74, 0xfb, 0x33, 0x4f, 0xf6, 0x30, 0x7c, 0xf1, 0x3b,
	0x00, 0x00, 0xff, 0xff, 0xc7, 0x17, 0xfe, 0x40, 0xe0, 0x03, 0x00, 0x00,
}
