# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/account.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "account.Account" do
    optional :id, :string, 1
    optional :hashed_password, :string, 2
    optional :role, :enum, 3, "account.Role"
    optional :player_id, :string, 4
    optional :name, :string, 5
  end
  add_message "account.Session" do
    optional :id, :string, 1
    optional :account_id, :string, 2
    optional :created_at, :int64, 3
    optional :role, :enum, 4, "account.Role"
  end
  add_enum "account.Role" do
    value :ADMIN, 0
    value :PLAYER, 1
  end
end

module Account
  Account = Google::Protobuf::DescriptorPool.generated_pool.lookup("account.Account").msgclass
  Session = Google::Protobuf::DescriptorPool.generated_pool.lookup("account.Session").msgclass
  Role = Google::Protobuf::DescriptorPool.generated_pool.lookup("account.Role").enummodule
end
