# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/api.proto

require 'google/protobuf'

require 'proto/comment_pb'
require 'proto/kifu_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "api.BoardResponse" do
    optional :board, :message, 1, "kifu.Board"
    repeated :comments, :message, 2, "comment.Comment"
  end
end

module Api
  BoardResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("api.BoardResponse").msgclass
end
