# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/api.proto

require 'google/protobuf'

require 'proto/comment_pb'
require 'proto/kifu_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "api.Step" do
    optional :kifu_id, :string, 1
    optional :seq, :int32, 2
    optional :start_ts, :int64, 3
    repeated :players, :message, 4, "kifu.Player"
  end
  add_message "api.BoardResponse" do
    optional :board, :message, 1, "kifu.Board"
    repeated :comments, :message, 2, "comment.Comment"
    repeated :steps, :message, 3, "api.Step"
  end
end

module Api
  Step = Google::Protobuf::DescriptorPool.generated_pool.lookup("api.Step").msgclass
  BoardResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("api.BoardResponse").msgclass
end
