# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/config.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "config.Config" do
    optional :script_name, :string, 1
    optional :port, :int32, 2
    optional :data_dir, :string, 3
    optional :kifu_index, :string, 4
    optional :step_index, :string, 5
    optional :account_index, :string, 6
    optional :comment_index, :string, 7
    optional :es_log, :bool, 8
  end
end

module Config
  Config = Google::Protobuf::DescriptorPool.generated_pool.lookup("config.Config").msgclass
end
