# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/index.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "index.Kifu" do
    optional :id, :string, 1
    repeated :first_players, :string, 2
    repeated :second_players, :string, 3
    optional :start_ts, :int64, 4
    optional :end_ts, :int64, 5
    repeated :board_ids, :string, 6
    optional :alias, :bool, 7
  end
  add_message "index.Step" do
    optional :id, :message, 1, "index.Step.StepId"
    optional :board_id, :string, 2
    optional :game_start_ts, :int64, 3
  end
  add_message "index.Step.StepId" do
    optional :kifu_id, :string, 1
    optional :seq, :int32, 2
    optional :finished, :bool, 3
  end
  add_message "index.Account" do
    optional :id, :string, 1
    optional :player_id, :string, 2
  end
end

module Index
  Kifu = Google::Protobuf::DescriptorPool.generated_pool.lookup("index.Kifu").msgclass
  Step = Google::Protobuf::DescriptorPool.generated_pool.lookup("index.Step").msgclass
  Step::StepId = Google::Protobuf::DescriptorPool.generated_pool.lookup("index.Step.StepId").msgclass
  Account = Google::Protobuf::DescriptorPool.generated_pool.lookup("index.Account").msgclass
end
