# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/kifu.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "kifu.Pos" do
    optional :x, :int32, 1
    optional :y, :int32, 2
  end
  add_message "kifu.Player" do
    optional :order, :enum, 1, "kifu.Player.Order"
    optional :name, :string, 2
  end
  add_enum "kifu.Player.Order" do
    value :FIRST, 0
    value :SECOND, 1
  end
  add_message "kifu.Piece" do
    optional :type, :enum, 1, "kifu.Piece.Type"
    optional :pos, :message, 2, "kifu.Pos"
    optional :order, :enum, 3, "kifu.Player.Order"
  end
  add_enum "kifu.Piece.Type" do
    value :NULL, 0
    value :GYOKU, 1
    value :KIN, 2
    value :GIN, 3
    value :NARI_GIN, 4
    value :KEI, 5
    value :NARI_KEI, 6
    value :KYOU, 7
    value :NARI_KYOU, 8
    value :KAKU, 9
    value :UMA, 10
    value :HISHA, 11
    value :RYU, 12
    value :FU, 13
    value :TO, 14
  end
  add_message "kifu.Step" do
    optional :seq, :int32, 1
    optional :pos, :message, 2, "kifu.Pos"
    optional :prev, :message, 3, "kifu.Pos"
    optional :piece, :enum, 4, "kifu.Piece.Type"
    optional :promoted, :bool, 5
    optional :putted, :bool, 6
    optional :player, :enum, 7, "kifu.Player.Order"
    optional :timestamp_sec, :int32, 8
    optional :thinking_sec, :int32, 9
  end
  add_message "kifu.Board" do
    optional :seq, :int32, 1
    repeated :pieces, :message, 2, "kifu.Piece"
  end
  add_message "kifu.Kifu" do
    optional :start_ts, :int64, 1
    optional :end_ts, :int64, 2
    optional :handicap, :string, 3
    optional :game_name, :string, 4
    optional :first_player, :message, 5, "kifu.Player"
    optional :second_player, :message, 6, "kifu.Player"
    repeated :steps, :message, 7, "kifu.Step"
    repeated :boards, :message, 8, "kifu.Board"
  end
end

module Kifu
  Pos = Google::Protobuf::DescriptorPool.generated_pool.lookup("kifu.Pos").msgclass
  Player = Google::Protobuf::DescriptorPool.generated_pool.lookup("kifu.Player").msgclass
  Player::Order = Google::Protobuf::DescriptorPool.generated_pool.lookup("kifu.Player.Order").enummodule
  Piece = Google::Protobuf::DescriptorPool.generated_pool.lookup("kifu.Piece").msgclass
  Piece::Type = Google::Protobuf::DescriptorPool.generated_pool.lookup("kifu.Piece.Type").enummodule
  Step = Google::Protobuf::DescriptorPool.generated_pool.lookup("kifu.Step").msgclass
  Board = Google::Protobuf::DescriptorPool.generated_pool.lookup("kifu.Board").msgclass
  Kifu = Google::Protobuf::DescriptorPool.generated_pool.lookup("kifu.Kifu").msgclass
end
