// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/kifu.proto

package kifu // import "github.com/nada-wagahai/kifulog/go/proto/kifu"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Player_Order int32

const (
	Player_FIRST  Player_Order = 0
	Player_SECOND Player_Order = 1
)

var Player_Order_name = map[int32]string{
	0: "FIRST",
	1: "SECOND",
}
var Player_Order_value = map[string]int32{
	"FIRST":  0,
	"SECOND": 1,
}

func (x Player_Order) String() string {
	return proto.EnumName(Player_Order_name, int32(x))
}
func (Player_Order) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_kifu_c79352f29b122ec9, []int{1, 0}
}

type Piece_Type int32

const (
	Piece_NULL      Piece_Type = 0
	Piece_GYOKU     Piece_Type = 1
	Piece_HISHA     Piece_Type = 2
	Piece_RYU       Piece_Type = 3
	Piece_KAKU      Piece_Type = 4
	Piece_UMA       Piece_Type = 5
	Piece_KIN       Piece_Type = 6
	Piece_GIN       Piece_Type = 7
	Piece_NARI_GIN  Piece_Type = 8
	Piece_KEI       Piece_Type = 9
	Piece_NARI_KEI  Piece_Type = 10
	Piece_KYOU      Piece_Type = 11
	Piece_NARI_KYOU Piece_Type = 12
	Piece_FU        Piece_Type = 13
	Piece_TO        Piece_Type = 14
)

var Piece_Type_name = map[int32]string{
	0:  "NULL",
	1:  "GYOKU",
	2:  "HISHA",
	3:  "RYU",
	4:  "KAKU",
	5:  "UMA",
	6:  "KIN",
	7:  "GIN",
	8:  "NARI_GIN",
	9:  "KEI",
	10: "NARI_KEI",
	11: "KYOU",
	12: "NARI_KYOU",
	13: "FU",
	14: "TO",
}
var Piece_Type_value = map[string]int32{
	"NULL":      0,
	"GYOKU":     1,
	"HISHA":     2,
	"RYU":       3,
	"KAKU":      4,
	"UMA":       5,
	"KIN":       6,
	"GIN":       7,
	"NARI_GIN":  8,
	"KEI":       9,
	"NARI_KEI":  10,
	"KYOU":      11,
	"NARI_KYOU": 12,
	"FU":        13,
	"TO":        14,
}

func (x Piece_Type) String() string {
	return proto.EnumName(Piece_Type_name, int32(x))
}
func (Piece_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_kifu_c79352f29b122ec9, []int{2, 0}
}

type Kifu_Format int32

const (
	Kifu_SHOGI24 Kifu_Format = 0
	Kifu_KIF     Kifu_Format = 1
)

var Kifu_Format_name = map[int32]string{
	0: "SHOGI24",
	1: "KIF",
}
var Kifu_Format_value = map[string]int32{
	"SHOGI24": 0,
	"KIF":     1,
}

func (x Kifu_Format) String() string {
	return proto.EnumName(Kifu_Format_name, int32(x))
}
func (Kifu_Format) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_kifu_c79352f29b122ec9, []int{5, 0}
}

type Pos struct {
	X                    int32    `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y                    int32    `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pos) Reset()         { *m = Pos{} }
func (m *Pos) String() string { return proto.CompactTextString(m) }
func (*Pos) ProtoMessage()    {}
func (*Pos) Descriptor() ([]byte, []int) {
	return fileDescriptor_kifu_c79352f29b122ec9, []int{0}
}
func (m *Pos) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pos.Unmarshal(m, b)
}
func (m *Pos) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pos.Marshal(b, m, deterministic)
}
func (dst *Pos) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pos.Merge(dst, src)
}
func (m *Pos) XXX_Size() int {
	return xxx_messageInfo_Pos.Size(m)
}
func (m *Pos) XXX_DiscardUnknown() {
	xxx_messageInfo_Pos.DiscardUnknown(m)
}

var xxx_messageInfo_Pos proto.InternalMessageInfo

func (m *Pos) GetX() int32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Pos) GetY() int32 {
	if m != nil {
		return m.Y
	}
	return 0
}

type Player struct {
	Order                Player_Order `protobuf:"varint,1,opt,name=order,proto3,enum=kifu.Player_Order" json:"order,omitempty"`
	Name                 string       `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Note                 string       `protobuf:"bytes,3,opt,name=note,proto3" json:"note,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Player) Reset()         { *m = Player{} }
func (m *Player) String() string { return proto.CompactTextString(m) }
func (*Player) ProtoMessage()    {}
func (*Player) Descriptor() ([]byte, []int) {
	return fileDescriptor_kifu_c79352f29b122ec9, []int{1}
}
func (m *Player) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Player.Unmarshal(m, b)
}
func (m *Player) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Player.Marshal(b, m, deterministic)
}
func (dst *Player) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Player.Merge(dst, src)
}
func (m *Player) XXX_Size() int {
	return xxx_messageInfo_Player.Size(m)
}
func (m *Player) XXX_DiscardUnknown() {
	xxx_messageInfo_Player.DiscardUnknown(m)
}

var xxx_messageInfo_Player proto.InternalMessageInfo

func (m *Player) GetOrder() Player_Order {
	if m != nil {
		return m.Order
	}
	return Player_FIRST
}

func (m *Player) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Player) GetNote() string {
	if m != nil {
		return m.Note
	}
	return ""
}

type Piece struct {
	Type                 Piece_Type   `protobuf:"varint,1,opt,name=type,proto3,enum=kifu.Piece_Type" json:"type,omitempty"`
	Pos                  *Pos         `protobuf:"bytes,2,opt,name=pos,proto3" json:"pos,omitempty"`
	Order                Player_Order `protobuf:"varint,3,opt,name=order,proto3,enum=kifu.Player_Order" json:"order,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Piece) Reset()         { *m = Piece{} }
func (m *Piece) String() string { return proto.CompactTextString(m) }
func (*Piece) ProtoMessage()    {}
func (*Piece) Descriptor() ([]byte, []int) {
	return fileDescriptor_kifu_c79352f29b122ec9, []int{2}
}
func (m *Piece) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Piece.Unmarshal(m, b)
}
func (m *Piece) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Piece.Marshal(b, m, deterministic)
}
func (dst *Piece) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Piece.Merge(dst, src)
}
func (m *Piece) XXX_Size() int {
	return xxx_messageInfo_Piece.Size(m)
}
func (m *Piece) XXX_DiscardUnknown() {
	xxx_messageInfo_Piece.DiscardUnknown(m)
}

var xxx_messageInfo_Piece proto.InternalMessageInfo

func (m *Piece) GetType() Piece_Type {
	if m != nil {
		return m.Type
	}
	return Piece_NULL
}

func (m *Piece) GetPos() *Pos {
	if m != nil {
		return m.Pos
	}
	return nil
}

func (m *Piece) GetOrder() Player_Order {
	if m != nil {
		return m.Order
	}
	return Player_FIRST
}

type Step struct {
	Seq                  int32        `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	Pos                  *Pos         `protobuf:"bytes,2,opt,name=pos,proto3" json:"pos,omitempty"`
	Prev                 *Pos         `protobuf:"bytes,3,opt,name=prev,proto3" json:"prev,omitempty"`
	Piece                Piece_Type   `protobuf:"varint,4,opt,name=piece,proto3,enum=kifu.Piece_Type" json:"piece,omitempty"`
	Promoted             bool         `protobuf:"varint,5,opt,name=promoted,proto3" json:"promoted,omitempty"`
	Putted               bool         `protobuf:"varint,6,opt,name=putted,proto3" json:"putted,omitempty"`
	Player               Player_Order `protobuf:"varint,7,opt,name=player,proto3,enum=kifu.Player_Order" json:"player,omitempty"`
	TimestampSec         int32        `protobuf:"varint,8,opt,name=timestamp_sec,json=timestampSec,proto3" json:"timestamp_sec,omitempty"`
	ThinkingSec          int32        `protobuf:"varint,9,opt,name=thinking_sec,json=thinkingSec,proto3" json:"thinking_sec,omitempty"`
	Finished             bool         `protobuf:"varint,10,opt,name=finished,proto3" json:"finished,omitempty"`
	Notes                []string     `protobuf:"bytes,11,rep,name=notes,proto3" json:"notes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Step) Reset()         { *m = Step{} }
func (m *Step) String() string { return proto.CompactTextString(m) }
func (*Step) ProtoMessage()    {}
func (*Step) Descriptor() ([]byte, []int) {
	return fileDescriptor_kifu_c79352f29b122ec9, []int{3}
}
func (m *Step) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Step.Unmarshal(m, b)
}
func (m *Step) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Step.Marshal(b, m, deterministic)
}
func (dst *Step) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Step.Merge(dst, src)
}
func (m *Step) XXX_Size() int {
	return xxx_messageInfo_Step.Size(m)
}
func (m *Step) XXX_DiscardUnknown() {
	xxx_messageInfo_Step.DiscardUnknown(m)
}

var xxx_messageInfo_Step proto.InternalMessageInfo

func (m *Step) GetSeq() int32 {
	if m != nil {
		return m.Seq
	}
	return 0
}

func (m *Step) GetPos() *Pos {
	if m != nil {
		return m.Pos
	}
	return nil
}

func (m *Step) GetPrev() *Pos {
	if m != nil {
		return m.Prev
	}
	return nil
}

func (m *Step) GetPiece() Piece_Type {
	if m != nil {
		return m.Piece
	}
	return Piece_NULL
}

func (m *Step) GetPromoted() bool {
	if m != nil {
		return m.Promoted
	}
	return false
}

func (m *Step) GetPutted() bool {
	if m != nil {
		return m.Putted
	}
	return false
}

func (m *Step) GetPlayer() Player_Order {
	if m != nil {
		return m.Player
	}
	return Player_FIRST
}

func (m *Step) GetTimestampSec() int32 {
	if m != nil {
		return m.TimestampSec
	}
	return 0
}

func (m *Step) GetThinkingSec() int32 {
	if m != nil {
		return m.ThinkingSec
	}
	return 0
}

func (m *Step) GetFinished() bool {
	if m != nil {
		return m.Finished
	}
	return false
}

func (m *Step) GetNotes() []string {
	if m != nil {
		return m.Notes
	}
	return nil
}

type Board struct {
	Pieces               []*Piece `protobuf:"bytes,1,rep,name=pieces,proto3" json:"pieces,omitempty"`
	Step                 *Step    `protobuf:"bytes,2,opt,name=step,proto3" json:"step,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Board) Reset()         { *m = Board{} }
func (m *Board) String() string { return proto.CompactTextString(m) }
func (*Board) ProtoMessage()    {}
func (*Board) Descriptor() ([]byte, []int) {
	return fileDescriptor_kifu_c79352f29b122ec9, []int{4}
}
func (m *Board) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Board.Unmarshal(m, b)
}
func (m *Board) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Board.Marshal(b, m, deterministic)
}
func (dst *Board) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Board.Merge(dst, src)
}
func (m *Board) XXX_Size() int {
	return xxx_messageInfo_Board.Size(m)
}
func (m *Board) XXX_DiscardUnknown() {
	xxx_messageInfo_Board.DiscardUnknown(m)
}

var xxx_messageInfo_Board proto.InternalMessageInfo

func (m *Board) GetPieces() []*Piece {
	if m != nil {
		return m.Pieces
	}
	return nil
}

func (m *Board) GetStep() *Step {
	if m != nil {
		return m.Step
	}
	return nil
}

type Kifu struct {
	StartTs              int64       `protobuf:"varint,1,opt,name=start_ts,json=startTs,proto3" json:"start_ts,omitempty"`
	EndTs                int64       `protobuf:"varint,2,opt,name=end_ts,json=endTs,proto3" json:"end_ts,omitempty"`
	Handicap             string      `protobuf:"bytes,3,opt,name=handicap,proto3" json:"handicap,omitempty"`
	GameName             string      `protobuf:"bytes,4,opt,name=game_name,json=gameName,proto3" json:"game_name,omitempty"`
	Players              []*Player   `protobuf:"bytes,5,rep,name=players,proto3" json:"players,omitempty"`
	Steps                []*Step     `protobuf:"bytes,6,rep,name=steps,proto3" json:"steps,omitempty"`
	BoardIds             []string    `protobuf:"bytes,7,rep,name=board_ids,json=boardIds,proto3" json:"board_ids,omitempty"`
	Alias                string      `protobuf:"bytes,8,opt,name=alias,proto3" json:"alias,omitempty"`
	Format               Kifu_Format `protobuf:"varint,9,opt,name=format,proto3,enum=kifu.Kifu_Format" json:"format,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Kifu) Reset()         { *m = Kifu{} }
func (m *Kifu) String() string { return proto.CompactTextString(m) }
func (*Kifu) ProtoMessage()    {}
func (*Kifu) Descriptor() ([]byte, []int) {
	return fileDescriptor_kifu_c79352f29b122ec9, []int{5}
}
func (m *Kifu) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Kifu.Unmarshal(m, b)
}
func (m *Kifu) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Kifu.Marshal(b, m, deterministic)
}
func (dst *Kifu) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Kifu.Merge(dst, src)
}
func (m *Kifu) XXX_Size() int {
	return xxx_messageInfo_Kifu.Size(m)
}
func (m *Kifu) XXX_DiscardUnknown() {
	xxx_messageInfo_Kifu.DiscardUnknown(m)
}

var xxx_messageInfo_Kifu proto.InternalMessageInfo

func (m *Kifu) GetStartTs() int64 {
	if m != nil {
		return m.StartTs
	}
	return 0
}

func (m *Kifu) GetEndTs() int64 {
	if m != nil {
		return m.EndTs
	}
	return 0
}

func (m *Kifu) GetHandicap() string {
	if m != nil {
		return m.Handicap
	}
	return ""
}

func (m *Kifu) GetGameName() string {
	if m != nil {
		return m.GameName
	}
	return ""
}

func (m *Kifu) GetPlayers() []*Player {
	if m != nil {
		return m.Players
	}
	return nil
}

func (m *Kifu) GetSteps() []*Step {
	if m != nil {
		return m.Steps
	}
	return nil
}

func (m *Kifu) GetBoardIds() []string {
	if m != nil {
		return m.BoardIds
	}
	return nil
}

func (m *Kifu) GetAlias() string {
	if m != nil {
		return m.Alias
	}
	return ""
}

func (m *Kifu) GetFormat() Kifu_Format {
	if m != nil {
		return m.Format
	}
	return Kifu_SHOGI24
}

type Metadata struct {
	KifuId               string   `protobuf:"bytes,1,opt,name=kifu_id,json=kifuId,proto3" json:"kifu_id,omitempty"`
	OwnerId              string   `protobuf:"bytes,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	UploadedTs           int64    `protobuf:"varint,3,opt,name=uploaded_ts,json=uploadedTs,proto3" json:"uploaded_ts,omitempty"`
	Note                 string   `protobuf:"bytes,4,opt,name=note,proto3" json:"note,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Metadata) Reset()         { *m = Metadata{} }
func (m *Metadata) String() string { return proto.CompactTextString(m) }
func (*Metadata) ProtoMessage()    {}
func (*Metadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_kifu_c79352f29b122ec9, []int{6}
}
func (m *Metadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Metadata.Unmarshal(m, b)
}
func (m *Metadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Metadata.Marshal(b, m, deterministic)
}
func (dst *Metadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Metadata.Merge(dst, src)
}
func (m *Metadata) XXX_Size() int {
	return xxx_messageInfo_Metadata.Size(m)
}
func (m *Metadata) XXX_DiscardUnknown() {
	xxx_messageInfo_Metadata.DiscardUnknown(m)
}

var xxx_messageInfo_Metadata proto.InternalMessageInfo

func (m *Metadata) GetKifuId() string {
	if m != nil {
		return m.KifuId
	}
	return ""
}

func (m *Metadata) GetOwnerId() string {
	if m != nil {
		return m.OwnerId
	}
	return ""
}

func (m *Metadata) GetUploadedTs() int64 {
	if m != nil {
		return m.UploadedTs
	}
	return 0
}

func (m *Metadata) GetNote() string {
	if m != nil {
		return m.Note
	}
	return ""
}

func init() {
	proto.RegisterType((*Pos)(nil), "kifu.Pos")
	proto.RegisterType((*Player)(nil), "kifu.Player")
	proto.RegisterType((*Piece)(nil), "kifu.Piece")
	proto.RegisterType((*Step)(nil), "kifu.Step")
	proto.RegisterType((*Board)(nil), "kifu.Board")
	proto.RegisterType((*Kifu)(nil), "kifu.Kifu")
	proto.RegisterType((*Metadata)(nil), "kifu.Metadata")
	proto.RegisterEnum("kifu.Player_Order", Player_Order_name, Player_Order_value)
	proto.RegisterEnum("kifu.Piece_Type", Piece_Type_name, Piece_Type_value)
	proto.RegisterEnum("kifu.Kifu_Format", Kifu_Format_name, Kifu_Format_value)
}

func init() { proto.RegisterFile("proto/kifu.proto", fileDescriptor_kifu_c79352f29b122ec9) }

var fileDescriptor_kifu_c79352f29b122ec9 = []byte{
	// 775 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x54, 0x5d, 0x6e, 0xdb, 0x46,
	0x10, 0x36, 0xc5, 0xff, 0x91, 0x6c, 0x6c, 0x17, 0xfd, 0x61, 0x13, 0xd4, 0x55, 0x98, 0x22, 0x50,
	0x0b, 0x44, 0x02, 0xd4, 0x5e, 0xc0, 0x69, 0x63, 0x9b, 0x90, 0x23, 0x19, 0x94, 0xf4, 0xe0, 0xbe,
	0x08, 0x6b, 0x71, 0x2d, 0x11, 0xb1, 0xb8, 0x2c, 0x77, 0xd5, 0x44, 0xbd, 0x49, 0x5f, 0x7b, 0x8b,
	0x5e, 0xa4, 0xe7, 0x29, 0x66, 0x48, 0xc9, 0xee, 0x83, 0x9b, 0x27, 0xcf, 0xf7, 0xe3, 0xd9, 0xe1,
	0x37, 0xda, 0x05, 0x56, 0x56, 0xca, 0xa8, 0xc1, 0xfb, 0xfc, 0x6e, 0xdb, 0xa7, 0x92, 0x3b, 0x58,
	0xc7, 0x2f, 0xc0, 0xbe, 0x56, 0x9a, 0x77, 0xc0, 0xfa, 0x18, 0x59, 0x5d, 0xab, 0xe7, 0xa6, 0xd6,
	0x47, 0x44, 0xbb, 0xa8, 0x55, 0xa3, 0x5d, 0xfc, 0x07, 0x78, 0xd7, 0xf7, 0x62, 0x27, 0x2b, 0xde,
	0x03, 0x57, 0x55, 0x99, 0xac, 0xc8, 0x79, 0x32, 0xe4, 0x7d, 0x6a, 0x57, 0x8b, 0xfd, 0x09, 0x2a,
	0x69, 0x6d, 0xe0, 0x1c, 0x9c, 0x42, 0x6c, 0x24, 0x35, 0x09, 0x53, 0xaa, 0x89, 0x53, 0x46, 0x46,
	0x76, 0xc3, 0x29, 0x23, 0xe3, 0x53, 0x70, 0xe9, 0xff, 0x78, 0x08, 0xee, 0x79, 0x92, 0x4e, 0x67,
	0xec, 0x88, 0x03, 0x78, 0xd3, 0xb7, 0x3f, 0x4f, 0xc6, 0xbf, 0x30, 0x2b, 0xfe, 0xb3, 0x05, 0xee,
	0x75, 0x2e, 0x97, 0x92, 0x7f, 0x07, 0x8e, 0xd9, 0x95, 0xb2, 0x39, 0x9a, 0x35, 0x47, 0xa3, 0xd4,
	0x9f, 0xed, 0x4a, 0x99, 0x92, 0xca, 0x9f, 0x83, 0x5d, 0x2a, 0x4d, 0xc7, 0xb6, 0x87, 0x61, 0x63,
	0x52, 0x3a, 0x45, 0xf6, 0x61, 0x7c, 0xfb, 0x13, 0xe3, 0xc7, 0x7f, 0x59, 0xe0, 0x60, 0x57, 0x1e,
	0x80, 0x33, 0x9e, 0x5f, 0x5d, 0xb1, 0x23, 0x1c, 0xf0, 0xe2, 0x66, 0x32, 0x9a, 0x33, 0x0b, 0xcb,
	0xcb, 0x64, 0x7a, 0x79, 0xc6, 0x5a, 0xdc, 0x07, 0x3b, 0xbd, 0x99, 0x33, 0x1b, 0x8d, 0xa3, 0xb3,
	0xd1, 0x9c, 0x39, 0x48, 0xcd, 0xdf, 0x9d, 0x31, 0x17, 0x8b, 0x51, 0x32, 0x66, 0x1e, 0x16, 0x17,
	0xc9, 0x98, 0xf9, 0xbc, 0x03, 0xc1, 0xf8, 0x2c, 0x4d, 0x16, 0x88, 0x02, 0xd2, 0xdf, 0x26, 0x2c,
	0x3c, 0xd0, 0x88, 0x80, 0x3a, 0xdd, 0x4c, 0xe6, 0xac, 0xcd, 0x8f, 0x21, 0xac, 0x79, 0x84, 0x1d,
	0xee, 0x41, 0xeb, 0x7c, 0xce, 0x8e, 0xf1, 0xef, 0x6c, 0xc2, 0x4e, 0xe2, 0x7f, 0x5a, 0xe0, 0x4c,
	0x8d, 0x2c, 0x39, 0x03, 0x5b, 0xcb, 0xdf, 0x9a, 0xf5, 0x61, 0xf9, 0xff, 0x31, 0x7c, 0x03, 0x4e,
	0x59, 0xc9, 0xdf, 0x29, 0x85, 0xff, 0xa8, 0x44, 0xf3, 0x57, 0xe0, 0x96, 0x18, 0x6b, 0xe4, 0x3c,
	0x91, 0x74, 0x2d, 0xf3, 0x67, 0x10, 0x94, 0x95, 0xda, 0x28, 0x23, 0xb3, 0xc8, 0xed, 0x5a, 0xbd,
	0x20, 0x3d, 0x60, 0xfe, 0x25, 0x78, 0xe5, 0xd6, 0xa0, 0xe2, 0x91, 0xd2, 0x20, 0xfe, 0x03, 0x78,
	0x25, 0xc5, 0x1d, 0xf9, 0x4f, 0xae, 0xa0, 0x71, 0xf0, 0x97, 0x70, 0x6c, 0xf2, 0x8d, 0xd4, 0x46,
	0x6c, 0xca, 0x85, 0x96, 0xcb, 0x28, 0xa0, 0xef, 0xeb, 0x1c, 0xc8, 0xa9, 0x5c, 0xf2, 0x17, 0xd0,
	0x31, 0xeb, 0xbc, 0x78, 0x9f, 0x17, 0x2b, 0xf2, 0x84, 0xe4, 0x69, 0xef, 0x39, 0xb4, 0x3c, 0x83,
	0xe0, 0x2e, 0x2f, 0x72, 0xbd, 0x96, 0x59, 0x04, 0xf5, 0x9c, 0x7b, 0xcc, 0x3f, 0x07, 0x17, 0x7f,
	0x86, 0x3a, 0x6a, 0x77, 0xed, 0x5e, 0x98, 0xd6, 0x20, 0xbe, 0x02, 0xf7, 0x8d, 0x12, 0x55, 0xc6,
	0x5f, 0x82, 0x47, 0xdf, 0xaa, 0x23, 0xab, 0x6b, 0xf7, 0xda, 0xc3, 0xf6, 0xa3, 0x2c, 0xd2, 0x46,
	0xe2, 0xa7, 0xe0, 0x68, 0x23, 0xcb, 0x26, 0x6c, 0xa8, 0x2d, 0xb8, 0x97, 0x94, 0xf8, 0xf8, 0xef,
	0x16, 0x38, 0xa3, 0xfc, 0x6e, 0xcb, 0xbf, 0x86, 0x40, 0x1b, 0x51, 0x99, 0x85, 0xd1, 0xb4, 0x2b,
	0x3b, 0xf5, 0x09, 0xcf, 0x34, 0xff, 0x02, 0x3c, 0x59, 0x64, 0x28, 0xb4, 0x48, 0x70, 0x65, 0x91,
	0xcd, 0x34, 0x8e, 0xbe, 0x16, 0x45, 0x96, 0x2f, 0x45, 0xd9, 0xdc, 0x9a, 0x03, 0xe6, 0xcf, 0x21,
	0x5c, 0x89, 0x8d, 0x5c, 0xd0, 0x35, 0x73, 0x6a, 0x11, 0x89, 0x31, 0x5e, 0xb5, 0x57, 0xe0, 0xd7,
	0x29, 0xea, 0xc8, 0xa5, 0xc9, 0x3b, 0x8f, 0x83, 0x4e, 0xf7, 0x22, 0xef, 0x82, 0x8b, 0x33, 0xea,
	0xc8, 0x23, 0xd7, 0xe3, 0xe1, 0x6b, 0x01, 0x8f, 0xb9, 0xc5, 0x2c, 0x16, 0x79, 0xa6, 0x23, 0x9f,
	0x52, 0x0a, 0x88, 0x48, 0x32, 0x8d, 0xf1, 0x89, 0xfb, 0x5c, 0x68, 0x5a, 0x4d, 0x98, 0xd6, 0x80,
	0x7f, 0x0f, 0xde, 0x9d, 0xaa, 0x36, 0xc2, 0xd0, 0x36, 0x4e, 0x86, 0x9f, 0xd5, 0x5d, 0x31, 0x83,
	0xfe, 0x39, 0x09, 0x69, 0x63, 0x88, 0x4f, 0xc1, 0xab, 0x19, 0xde, 0x06, 0x7f, 0x7a, 0x39, 0xb9,
	0x48, 0x86, 0x3f, 0xb1, 0xa3, 0xfa, 0xe6, 0x9c, 0x33, 0x2b, 0xd6, 0x10, 0xbc, 0x93, 0x46, 0x64,
	0xc2, 0x08, 0xfe, 0x15, 0xf8, 0xd8, 0x67, 0x91, 0x67, 0x94, 0x5e, 0x98, 0x7a, 0x08, 0x93, 0x0c,
	0x73, 0x55, 0x1f, 0x0a, 0x59, 0xa1, 0x52, 0xbf, 0x37, 0x3e, 0xe1, 0x24, 0xe3, 0xdf, 0x42, 0x7b,
	0x5b, 0xde, 0x2b, 0x91, 0x49, 0x0a, 0xd7, 0xa6, 0x70, 0x61, 0x4f, 0xcd, 0xf4, 0xe1, 0x4d, 0x72,
	0x1e, 0xde, 0xa4, 0x37, 0x83, 0x5f, 0x5f, 0xaf, 0x72, 0xb3, 0xde, 0xde, 0xf6, 0x97, 0x6a, 0x33,
	0x28, 0x44, 0x26, 0x5e, 0x7f, 0x10, 0x2b, 0xb1, 0x16, 0x39, 0x3d, 0x9f, 0xf7, 0x6a, 0x35, 0x58,
	0xa9, 0xc1, 0xc3, 0x7b, 0x7a, 0xeb, 0x51, 0xfd, 0xe3, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xc7,
	0xef, 0x33, 0xe4, 0x64, 0x05, 0x00, 0x00,
}
