// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/account.proto

package account // import "github.com/nada-wagahai/kifulog/go/proto/account"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Role int32

const (
	Role_ADMIN  Role = 0
	Role_PLAYER Role = 1
)

var Role_name = map[int32]string{
	0: "ADMIN",
	1: "PLAYER",
}
var Role_value = map[string]int32{
	"ADMIN":  0,
	"PLAYER": 1,
}

func (x Role) String() string {
	return proto.EnumName(Role_name, int32(x))
}
func (Role) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_account_ef9d3bee42563ab6, []int{0}
}

type Account struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	HashedPassword       string   `protobuf:"bytes,2,opt,name=hashed_password,json=hashedPassword,proto3" json:"hashed_password,omitempty"`
	Role                 Role     `protobuf:"varint,3,opt,name=role,proto3,enum=account.Role" json:"role,omitempty"`
	PlayerId             string   `protobuf:"bytes,4,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Name                 string   `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Account) Reset()         { *m = Account{} }
func (m *Account) String() string { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()    {}
func (*Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_ef9d3bee42563ab6, []int{0}
}
func (m *Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account.Unmarshal(m, b)
}
func (m *Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account.Marshal(b, m, deterministic)
}
func (dst *Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account.Merge(dst, src)
}
func (m *Account) XXX_Size() int {
	return xxx_messageInfo_Account.Size(m)
}
func (m *Account) XXX_DiscardUnknown() {
	xxx_messageInfo_Account.DiscardUnknown(m)
}

var xxx_messageInfo_Account proto.InternalMessageInfo

func (m *Account) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Account) GetHashedPassword() string {
	if m != nil {
		return m.HashedPassword
	}
	return ""
}

func (m *Account) GetRole() Role {
	if m != nil {
		return m.Role
	}
	return Role_ADMIN
}

func (m *Account) GetPlayerId() string {
	if m != nil {
		return m.PlayerId
	}
	return ""
}

func (m *Account) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Session struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AccountId            string   `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	CreatedAt            int64    `protobuf:"varint,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Role                 Role     `protobuf:"varint,4,opt,name=role,proto3,enum=account.Role" json:"role,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Session) Reset()         { *m = Session{} }
func (m *Session) String() string { return proto.CompactTextString(m) }
func (*Session) ProtoMessage()    {}
func (*Session) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_ef9d3bee42563ab6, []int{1}
}
func (m *Session) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Session.Unmarshal(m, b)
}
func (m *Session) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Session.Marshal(b, m, deterministic)
}
func (dst *Session) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Session.Merge(dst, src)
}
func (m *Session) XXX_Size() int {
	return xxx_messageInfo_Session.Size(m)
}
func (m *Session) XXX_DiscardUnknown() {
	xxx_messageInfo_Session.DiscardUnknown(m)
}

var xxx_messageInfo_Session proto.InternalMessageInfo

func (m *Session) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Session) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

func (m *Session) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *Session) GetRole() Role {
	if m != nil {
		return m.Role
	}
	return Role_ADMIN
}

func init() {
	proto.RegisterType((*Account)(nil), "account.Account")
	proto.RegisterType((*Session)(nil), "account.Session")
	proto.RegisterEnum("account.Role", Role_name, Role_value)
}

func init() { proto.RegisterFile("proto/account.proto", fileDescriptor_account_ef9d3bee42563ab6) }

var fileDescriptor_account_ef9d3bee42563ab6 = []byte{
	// 277 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0x4d, 0x9a, 0x36, 0x66, 0xc0, 0x58, 0xd6, 0x4b, 0x40, 0x0a, 0xb5, 0x17, 0x8b, 0x60,
	0x22, 0xf5, 0x09, 0x22, 0x7a, 0x08, 0xa8, 0x94, 0x78, 0xd2, 0x4b, 0x98, 0x66, 0xd7, 0x64, 0x31,
	0xcd, 0x84, 0x64, 0x43, 0xd1, 0x07, 0xf1, 0x79, 0xa5, 0x9b, 0x55, 0x10, 0xf1, 0x36, 0xff, 0xf7,
	0xc3, 0xcc, 0xc7, 0xc0, 0x49, 0xd3, 0x92, 0xa2, 0x08, 0xf3, 0x9c, 0xfa, 0x5a, 0x85, 0x3a, 0x31,
	0xd7, 0xc4, 0xc5, 0xa7, 0x05, 0x6e, 0x3c, 0xcc, 0xcc, 0x07, 0x5b, 0xf2, 0xc0, 0x9a, 0x5b, 0x4b,
	0x2f, 0xb5, 0x25, 0x67, 0xe7, 0x70, 0x5c, 0x62, 0x57, 0x0a, 0x9e, 0x35, 0xd8, 0x75, 0x3b, 0x6a,
	0x79, 0x60, 0xeb, 0xd2, 0x1f, 0xf0, 0xda, 0x50, 0x76, 0x06, 0x4e, 0x4b, 0x95, 0x08, 0x46, 0x73,
	0x6b, 0xe9, 0xaf, 0x8e, 0xc2, 0xef, 0x5b, 0x29, 0x55, 0x22, 0xd5, 0x15, 0x3b, 0x05, 0xaf, 0xa9,
	0xf0, 0x5d, 0xb4, 0x99, 0xe4, 0x81, 0xa3, 0xb7, 0x1c, 0x0e, 0x20, 0xe1, 0x8c, 0x81, 0x53, 0xe3,
	0x56, 0x04, 0x63, 0xcd, 0xf5, 0xbc, 0xf8, 0x00, 0xf7, 0x49, 0x74, 0x9d, 0xa4, 0xfa, 0x8f, 0xd7,
	0x0c, 0xc0, 0x5c, 0xd8, 0x2f, 0x1b, 0x94, 0x3c, 0x43, 0x12, 0x5d, 0xe7, 0xad, 0x40, 0x25, 0x78,
	0x86, 0x4a, 0x3b, 0x8d, 0x52, 0xcf, 0x90, 0x58, 0xfd, 0xc8, 0x3a, 0xff, 0xca, 0x5e, 0xcc, 0xc0,
	0xd9, 0x27, 0xe6, 0xc1, 0x38, 0xbe, 0x7d, 0x48, 0x1e, 0xa7, 0x07, 0x0c, 0x60, 0xb2, 0xbe, 0x8f,
	0x9f, 0xef, 0xd2, 0xa9, 0x75, 0xb3, 0x7a, 0xb9, 0x2a, 0xa4, 0x2a, 0xfb, 0x4d, 0x98, 0xd3, 0x36,
	0xaa, 0x91, 0xe3, 0xe5, 0x0e, 0x0b, 0x2c, 0x51, 0x46, 0x6f, 0xf2, 0xb5, 0xaf, 0xa8, 0x88, 0x0a,
	0x8a, 0x7e, 0xbd, 0x7d, 0x33, 0xd1, 0xf1, 0xfa, 0x2b, 0x00, 0x00, 0xff, 0xff, 0x50, 0xf4, 0xa0,
	0x8d, 0x8e, 0x01, 0x00, 0x00,
}
